- name: Install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - maven
    - mysql

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    comment: "Roboshop system user"
    home: /app
    system: true

- name: Delete app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Deleting shipping application
  ansible.builtin.file:
    path: /tmp/shipping.zip
    state: absent
  
- name: Download shipping application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
    dest: /tmp/shipping.zip

- name: extract shipping application
  ansible.builtin.unarchive:
    src: /tmp/shipping.zip 
    dest: /app
    remote_src: yes

- name: Change directory
  ansible.builtin.command:
  args:
    chdir: /app

- name: Installing maven packages
  ansible.builtin.command:  mvn clean package 

- name: move jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar

- name: copying shipping services
  ansible.builtin.file:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Enable and start shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: started
    enabled: true
    daemon_reload: true

- name: import shipping data into mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: mysql.someshwar.fun
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: restart shipping services
  ansible.builtin.service:
    name: shipping
    state: restarted