
- name: Install python
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python3
  - gcc
  - python3-devel

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    comment: "Roboshop system user"
    home: /app
    system: true

- name: Delete app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Deleting payment application
  ansible.builtin.file:
    path: /tmp/payment.zip
    state: absent
  
- name: Download payment application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
    dest: /tmp/payment.zip

- name: extract payment application
  ansible.builtin.unarchive:
    src: /tmp/payment.zip 
    dest: /app
    remote_src: yes

- name: Change directory
  ansible.builtin.command:
    chdir: /app

- name: Install dependencies
  ansible.builtin.command: pip3 install -r requirements.txt

- name: copying payment services
  ansible.builtin.file:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: Enable and start payment
  ansible.builtin.systemd_service:
    name: payment
    state: started
    enabled: true
    daemon_reload: true