- name: copy rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq
  ansible.builtin.command: dnf install rabbitmq-server -y

- name: start and enable services
  ansible.builtin.service:
    name: rabbitmq-server
    start: started
    enabled: yes

- name: create and provide permissions to user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
