- name: Disabling node
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enabling node
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Installing nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app
    comment: "roboshop system user"
    system: true

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading catalogue
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Unarchive catalogue file
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: copying catalogue service
  ansible.builtin.copy:
    name: catalogue
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongo client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh mongodb.daws86s.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host mongodb.daws86s.fun </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: daemon reload enable and start
  ansible.builtin.systemd_service:
    name: catalogue
    enabled: true
    state: started
    daemon_reload: true
