- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app
    comment: "roboshop system user"
    system: true

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent
    
- name: creating app directory
  ansible.builtin.file:
    state: directory
    path: /app

- name: Delete catalogue file
  ansible.builtin.file:
    path: /tmp/catalogue.zip
    state: absent

- name: Downloading catalogue application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: extract catalogue application
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: Change directory
  ansible.builtin.command:
  args:
    chdir: /app