- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabling nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    comment: "Roboshop system user"
    home: /app
    system: true

- name: Delete app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Deleting cart application
  ansible.builtin.file:
    path: /tmp/cart.zip
    state: absent
  
- name: Download cart application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
    dest: /tmp/cart.zip

- name: extract cart application
  ansible.builtin.unarchive:
    src: /tmp/cart.zip 
    dest: /app
    remote_src: yes

- name: Change directory
  ansible.builtin.command:
    chdir: /app
 
- name: Install nodejs dependencies
  community.general.npm:
    name: npm
    path: /app

- name: copying cart services
  ansible.builtin.file:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Enable and start cart
  ansible.builtin.systemd_service:
    name: cart
    state: started
    enabled: true
    daemon_reload: true

